config/routes.rb
Rails.application.routes.draw do
  resources :vehicles do
    get 'inventory', to: 'vehicles#inventory', on: :collection
  end
  root 'vehicles#index'
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  def self.format_inventory
    inventory = {}
    all_vehicles = Vehicle.all
    inventory["resultCount"] = all_vehicles.count
    inventory["results"] = []
    all_vehicles.each do |v|
      inventory["results"] << v
    end
    inventory
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  def inventory
    @inventory = Vehicle.format_inventory
    render json: @inventory 
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:vehicle_make, :vehicle_model, :vehicle_year, :dept_number, :updated_by, :last_updated, :mileage, :checked_in)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Vehicle Inventory'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Vehicle Inventory'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/vehicles/_form.html.haml
= simple_form_for(@vehicle) do |f|
  = f.error_notification

  .form-inputs
    = f.input :vehicle_make
    = f.input :vehicle_model
    = f.input :vehicle_year
    = f.input :dept_number
    = f.input :updated_by
    = f.input :last_updated
    = f.input :mileage
    = f.input :checked_in

  .form-actions
    = f.button :submit

app/views/vehicles/edit.html.haml
%h1 Editing vehicle

= render 'form'

= link_to 'Show', @vehicle
\|
= link_to 'Back', vehicles_path

app/views/vehicles/index.html.haml
%h1 Listing vehicles

%table
  %thead
    %tr
      %th Vehicle make
      %th Vehicle model
      %th Vehicle year
      %th Dept number
      %th Updated by
      %th Last updated
      %th Mileage
      %th Checked in
      %th
      %th
      %th
      
  %tbody
    - @vehicles.each do |vehicle|
      %tr
        %td= vehicle.vehicle_make
        %td= vehicle.vehicle_model
        %td= vehicle.vehicle_year
        %td= vehicle.dept_number
        %td= vehicle.updated_by
        %td= vehicle.last_updated
        %td= vehicle.mileage
        %td= vehicle.checked_in
        %td= link_to 'Show', vehicle
        %td= link_to 'Edit', edit_vehicle_path(vehicle)
        %td= link_to 'Destroy', vehicle, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Vehicle', new_vehicle_path

app/views/vehicles/new.html.haml
%h1 New vehicle

= render 'form'

= link_to 'Back', vehicles_path

app/views/vehicles/show.html.haml
%p#notice= notice

%p
  %b Vehicle make:
  = @vehicle.vehicle_make
%p
  %b Vehicle model:
  = @vehicle.vehicle_model
%p
  %b Vehicle year:
  = @vehicle.vehicle_year
%p
  %b Dept number:
  = @vehicle.dept_number
%p
  %b Updated by:
  = @vehicle.updated_by
%p
  %b Last updated:
  = @vehicle.last_updated
%p
  %b Mileage:
  = @vehicle.mileage
%p
  %b Checked in:
  = @vehicle.checked_in

= link_to 'Edit', edit_vehicle_path(@vehicle)
\|
= link_to 'Back', vehicles_path